from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QPushButton,
    QSplitter,
    QStackedWidget,
    QTableWidget,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from .ui_helpers import configure_readonly_table


def build_name_editor_page(window, *, tr):
    page = QWidget()
    root = QVBoxLayout(page)
    root.setContentsMargins(10, 10, 10, 10)
    root.setSpacing(8)

    window.name_title_lbl = QLabel(tr("name.title"))
    window.name_title_lbl.setStyleSheet("font-size: 15pt; font-weight: bold;")
    root.addWidget(window.name_title_lbl)
    window.name_subtitle_lbl = QLabel(tr("name.subtitle"))
    window.name_subtitle_lbl.setWordWrap(True)
    window.name_subtitle_lbl.setStyleSheet("")
    root.addWidget(window.name_subtitle_lbl)

    sub_nav = QWidget()
    snl = QHBoxLayout(sub_nav)
    snl.setContentsMargins(0, 0, 0, 0)
    snl.setSpacing(0)
    window.name_subnav_name_btn = QPushButton(tr("name.tab.names"))
    window.name_subnav_info_btn = QPushButton(tr("name.tab.info"))
    for btn in (window.name_subnav_name_btn, window.name_subnav_info_btn):
        btn.setCheckable(True)
        btn.setAutoExclusive(True)
        snl.addWidget(btn)
    window._apply_global_nav_tab_style()
    snl.addStretch(1)
    root.addWidget(sub_nav)

    window.name_info_stack = QStackedWidget()
    root.addWidget(window.name_info_stack, 1)

    name_page = QWidget()
    nroot = QVBoxLayout(name_page)
    nroot.setContentsMargins(0, 0, 0, 0)
    nroot.setSpacing(8)

    filter_row = QWidget()
    fl = QHBoxLayout(filter_row)
    fl.setContentsMargins(0, 0, 0, 0)
    fl.setSpacing(6)
    window.name_search_lbl = QLabel(tr("name.search"))
    fl.addWidget(window.name_search_lbl)
    window.name_search_edit = QLineEdit()
    window.name_search_edit.setPlaceholderText(tr("name.search.placeholder"))
    fl.addWidget(window.name_search_edit, 1)
    window.name_clear_filters_btn = QPushButton(tr("name.btn.clear_filters"))
    window.name_clear_filters_btn.clicked.connect(window._name_editor_clear_filters)
    fl.addWidget(window.name_clear_filters_btn)
    window.name_reload_page_btn = QPushButton(tr("name.btn.reload"))
    window.name_reload_page_btn.clicked.connect(window._open_name_editor_view)
    fl.addWidget(window.name_reload_page_btn)
    window.name_conflicts_page_btn = QPushButton(tr("name.btn.conflicts"))
    window.name_conflicts_page_btn.clicked.connect(window._name_editor_check_conflicts)
    fl.addWidget(window.name_conflicts_page_btn)
    nroot.addWidget(filter_row)

    split = QSplitter(Qt.Vertical)
    nroot.addWidget(split, 1)

    top = QWidget()
    tl = QVBoxLayout(top)
    tl.setContentsMargins(0, 0, 0, 0)
    tl.setSpacing(6)
    window.name_ids_table = QTableWidget(0, 4)
    configure_readonly_table(window.name_ids_table)
    window.name_ids_table.setHorizontalHeaderLabels(
        [tr("name.col.id"), tr("name.col.text"), tr("name.col.dll"), tr("name.col.editable")]
    )
    h = window.name_ids_table.horizontalHeader()
    h.setSectionResizeMode(0, QHeaderView.ResizeToContents)
    h.setSectionResizeMode(1, QHeaderView.Stretch)
    h.setSectionResizeMode(2, QHeaderView.ResizeToContents)
    h.setSectionResizeMode(3, QHeaderView.ResizeToContents)
    tl.addWidget(window.name_ids_table, 1)

    er = QWidget()
    erl = QHBoxLayout(er)
    erl.setContentsMargins(0, 0, 0, 0)
    erl.setSpacing(6)
    window.name_selected_id_lbl = QLabel(tr("name.selected_id"))
    erl.addWidget(window.name_selected_id_lbl)
    window.name_selected_id_edit = QLineEdit()
    window.name_selected_id_edit.setReadOnly(True)
    window.name_selected_id_edit.setMaximumWidth(160)
    erl.addWidget(window.name_selected_id_edit)
    window.name_text_lbl = QLabel(tr("name.text"))
    erl.addWidget(window.name_text_lbl)
    window.name_text_edit = QLineEdit()
    erl.addWidget(window.name_text_edit, 1)
    window.name_update_page_btn = QPushButton(tr("name.btn.update"))
    window.name_update_page_btn.clicked.connect(window._name_editor_update_selected)
    erl.addWidget(window.name_update_page_btn)
    window.name_create_page_btn = QPushButton(tr("name.btn.create"))
    window.name_create_page_btn.clicked.connect(window._name_editor_create_entry)
    erl.addWidget(window.name_create_page_btn)
    window.name_jump_page_btn = QPushButton(tr("btn.jump"))
    window.name_jump_page_btn.clicked.connect(window._name_editor_jump_to_selected_usage)
    erl.addWidget(window.name_jump_page_btn)
    tl.addWidget(er)

    window.name_usage_title_lbl = QLabel(tr("name.usage.title"))
    window.name_usage_title_lbl.setStyleSheet("font-weight:bold;")
    tl.addWidget(window.name_usage_title_lbl)
    window.name_usage_table = QTableWidget(0, 5)
    configure_readonly_table(window.name_usage_table)
    window.name_usage_table.setHorizontalHeaderLabels(
        [tr("name.col.system"), tr("name.col.section"), tr("name.col.nickname"), tr("name.col.archetype"), tr("name.col.file")]
    )
    hu = window.name_usage_table.horizontalHeader()
    hu.setSectionResizeMode(0, QHeaderView.ResizeToContents)
    hu.setSectionResizeMode(1, QHeaderView.ResizeToContents)
    hu.setSectionResizeMode(2, QHeaderView.Stretch)
    hu.setSectionResizeMode(3, QHeaderView.ResizeToContents)
    hu.setSectionResizeMode(4, QHeaderView.ResizeToContents)
    tl.addWidget(window.name_usage_table, 1)
    split.addWidget(top)

    bottom = QWidget()
    bl = QVBoxLayout(bottom)
    bl.setContentsMargins(0, 0, 0, 0)
    bl.setSpacing(6)
    window.name_missing_title_lbl = QLabel(tr("name.missing.title"))
    window.name_missing_title_lbl.setStyleSheet("font-weight:bold;")
    bl.addWidget(window.name_missing_title_lbl)
    window.name_missing_table = QTableWidget(0, 5)
    configure_readonly_table(window.name_missing_table)
    window.name_missing_table.setHorizontalHeaderLabels(
        [tr("name.col.system"), tr("name.col.section"), tr("name.col.nickname"), tr("name.col.archetype"), tr("name.col.file")]
    )
    hm = window.name_missing_table.horizontalHeader()
    hm.setSectionResizeMode(0, QHeaderView.ResizeToContents)
    hm.setSectionResizeMode(1, QHeaderView.ResizeToContents)
    hm.setSectionResizeMode(2, QHeaderView.Stretch)
    hm.setSectionResizeMode(3, QHeaderView.ResizeToContents)
    hm.setSectionResizeMode(4, QHeaderView.ResizeToContents)
    bl.addWidget(window.name_missing_table, 1)
    mr = QWidget()
    mrl = QHBoxLayout(mr)
    mrl.setContentsMargins(0, 0, 0, 0)
    mrl.setSpacing(6)
    window.name_missing_text_lbl = QLabel(tr("name.assign_text"))
    mrl.addWidget(window.name_missing_text_lbl)
    window.name_missing_text_edit = QLineEdit()
    mrl.addWidget(window.name_missing_text_edit, 1)
    window.name_assign_page_btn = QPushButton(tr("name.btn.assign_missing"))
    window.name_assign_page_btn.clicked.connect(window._name_editor_assign_missing_selected)
    mrl.addWidget(window.name_assign_page_btn)
    bl.addWidget(mr)
    split.addWidget(bottom)
    split.setSizes([430, 270])

    info_page = QWidget()
    iroot = QVBoxLayout(info_page)
    iroot.setContentsMargins(0, 0, 0, 0)
    iroot.setSpacing(8)
    window.info_editor_subtitle_lbl = QLabel(tr("info.subtitle"))
    window.info_editor_subtitle_lbl.setWordWrap(True)
    window.info_editor_subtitle_lbl.setStyleSheet("")
    iroot.addWidget(window.info_editor_subtitle_lbl)

    ifilter = QWidget()
    ifl = QHBoxLayout(ifilter)
    ifl.setContentsMargins(0, 0, 0, 0)
    ifl.setSpacing(6)
    window.info_search_lbl = QLabel(tr("info.search"))
    ifl.addWidget(window.info_search_lbl)
    window.info_search_edit = QLineEdit()
    window.info_search_edit.setPlaceholderText(tr("info.search.placeholder"))
    ifl.addWidget(window.info_search_edit, 1)
    window.info_reload_btn = QPushButton(tr("info.btn.reload"))
    window.info_reload_btn.clicked.connect(window._open_name_editor_view)
    ifl.addWidget(window.info_reload_btn)
    iroot.addWidget(ifilter)

    fmt_row = QWidget()
    fml = QHBoxLayout(fmt_row)
    fml.setContentsMargins(0, 0, 0, 0)
    fml.setSpacing(4)
    window.info_builder_format_lbl = QLabel(tr("info.builder.field.format"))
    fml.addWidget(window.info_builder_format_lbl)
    window.info_fmt_bold_btn = QPushButton(tr("info.builder.btn.bold"))
    window.info_fmt_bold_btn.setCheckable(True)
    window.info_fmt_italic_btn = QPushButton(tr("info.builder.btn.italic"))
    window.info_fmt_italic_btn.setCheckable(True)
    window.info_fmt_underline_btn = QPushButton(tr("info.builder.btn.underline"))
    window.info_fmt_underline_btn.setCheckable(True)
    window.info_fmt_align_left_btn = QPushButton(tr("info.builder.btn.align_left"))
    window.info_fmt_align_left_btn.setCheckable(True)
    window.info_fmt_align_center_btn = QPushButton(tr("info.builder.btn.align_center"))
    window.info_fmt_align_center_btn.setCheckable(True)
    window.info_fmt_align_right_btn = QPushButton(tr("info.builder.btn.align_right"))
    window.info_fmt_align_right_btn.setCheckable(True)
    for btn in (
        window.info_fmt_bold_btn,
        window.info_fmt_italic_btn,
        window.info_fmt_underline_btn,
        window.info_fmt_align_left_btn,
        window.info_fmt_align_center_btn,
        window.info_fmt_align_right_btn,
    ):
        btn.setMinimumWidth(30)
        fml.addWidget(btn)
    window.info_fmt_align_left_btn.setChecked(True)
    window.info_fmt_align_left_btn.clicked.connect(lambda _=False: window._info_builder_set_align("left"))
    window.info_fmt_align_center_btn.clicked.connect(lambda _=False: window._info_builder_set_align("center"))
    window.info_fmt_align_right_btn.clicked.connect(lambda _=False: window._info_builder_set_align("right"))
    window.info_builder_color_lbl = QLabel(tr("info.builder.field.color"))
    fml.addWidget(window.info_builder_color_lbl)
    window.info_builder_color_edit = QLineEdit("default")
    window.info_builder_color_edit.setMaximumWidth(130)
    fml.addWidget(window.info_builder_color_edit)
    window.info_builder_color_pick_btn = QPushButton(tr("info.builder.btn.color_pick"))
    window.info_builder_color_pick_btn.clicked.connect(window._info_builder_pick_color)
    fml.addWidget(window.info_builder_color_pick_btn)
    window.info_builder_color_reset_btn = QPushButton(tr("info.builder.btn.color_default"))
    window.info_builder_color_reset_btn.clicked.connect(window._info_builder_reset_color)
    fml.addWidget(window.info_builder_color_reset_btn)
    fml.addStretch(1)
    iroot.addWidget(fmt_row)

    info_split = QSplitter(Qt.Horizontal)
    iroot.addWidget(info_split, 1)

    info_left = QWidget()
    ill = QVBoxLayout(info_left)
    ill.setContentsMargins(0, 0, 0, 0)
    ill.setSpacing(6)
    window.info_ids_table = QTableWidget(0, 4)
    configure_readonly_table(window.info_ids_table)
    window.info_ids_table.setHorizontalHeaderLabels(
        [tr("info.col.id"), tr("info.col.preview"), tr("info.col.dll"), tr("info.col.editable")]
    )
    ih = window.info_ids_table.horizontalHeader()
    ih.setSectionResizeMode(0, QHeaderView.ResizeToContents)
    ih.setSectionResizeMode(1, QHeaderView.Stretch)
    ih.setSectionResizeMode(2, QHeaderView.ResizeToContents)
    ih.setSectionResizeMode(3, QHeaderView.ResizeToContents)
    ill.addWidget(window.info_ids_table, 1)
    info_split.addWidget(info_left)

    info_right = QWidget()
    irl = QVBoxLayout(info_right)
    irl.setContentsMargins(0, 0, 0, 0)
    irl.setSpacing(6)
    sel_row = QWidget()
    srl = QHBoxLayout(sel_row)
    srl.setContentsMargins(0, 0, 0, 0)
    srl.setSpacing(6)
    window.info_selected_id_lbl = QLabel(tr("info.selected_id"))
    srl.addWidget(window.info_selected_id_lbl)
    window.info_selected_id_edit = QLineEdit()
    window.info_selected_id_edit.setReadOnly(True)
    window.info_selected_id_edit.setMaximumWidth(160)
    srl.addWidget(window.info_selected_id_edit)
    window.info_dll_lbl = QLabel(tr("info.source_dll"))
    srl.addWidget(window.info_dll_lbl)
    window.info_dll_edit = QLineEdit()
    window.info_dll_edit.setReadOnly(True)
    srl.addWidget(window.info_dll_edit, 1)
    irl.addWidget(sel_row)
    window.info_preview_lbl = QLabel(tr("info.preview"))
    window.info_preview_lbl.setStyleSheet("font-weight:bold;")
    irl.addWidget(window.info_preview_lbl)
    window.info_editor_split = QSplitter(Qt.Vertical)
    irl.addWidget(window.info_editor_split, 1)
    window.info_live_edit = QTextEdit()
    window.info_live_edit.setAcceptRichText(True)
    window.info_live_edit.setReadOnly(False)
    window.info_editor_split.addWidget(window.info_live_edit)
    xml_wrap = QWidget()
    xwl = QVBoxLayout(xml_wrap)
    xwl.setContentsMargins(0, 0, 0, 0)
    xwl.setSpacing(4)
    window.info_xml_lbl = QLabel(tr("info.xml"))
    window.info_xml_lbl.setStyleSheet("font-weight:bold;")
    xwl.addWidget(window.info_xml_lbl)
    window.info_xml_edit = QTextEdit()
    window.info_xml_edit.setAcceptRichText(False)
    window.info_xml_edit.setPlainText(window._default_infocard_xml_template())
    xwl.addWidget(window.info_xml_edit, 1)
    window.info_editor_split.addWidget(xml_wrap)
    window.info_editor_split.setSizes([340, 240])
    ib = QWidget()
    ibl = QHBoxLayout(ib)
    ibl.setContentsMargins(0, 0, 0, 0)
    ibl.setSpacing(6)
    window.info_validate_btn = QPushButton(tr("info.btn.validate"))
    window.info_validate_btn.clicked.connect(window._info_editor_validate_xml)
    ibl.addWidget(window.info_validate_btn)
    window.info_create_btn = QPushButton(tr("info.btn.create"))
    window.info_create_btn.clicked.connect(window._info_editor_create_entry)
    ibl.addWidget(window.info_create_btn)
    window.info_update_btn = QPushButton(tr("info.btn.update"))
    window.info_update_btn.clicked.connect(window._info_editor_update_selected)
    ibl.addWidget(window.info_update_btn)
    window.info_jump_btn = QPushButton(tr("btn.jump"))
    window.info_jump_btn.clicked.connect(window._info_editor_jump_to_selected_usage)
    ibl.addWidget(window.info_jump_btn)
    ibl.addStretch(1)
    irl.addWidget(ib)
    window.info_note_lbl = QLabel(tr("info.note"))
    window.info_note_lbl.setWordWrap(True)
    window.info_note_lbl.setStyleSheet("")
    irl.addWidget(window.info_note_lbl)
    info_split.addWidget(info_right)
    info_split.setSizes([460, 640])

    window.name_info_stack.addWidget(name_page)
    window.name_info_stack.addWidget(info_page)

    window._name_editor_name_rows = []
    window._name_editor_missing_rows = []
    window._name_editor_usage_map = {}
    window._info_editor_rows = []
    window._info_editor_usage_map = {}
    window._info_sync_busy = False
    window.name_search_edit.textChanged.connect(window._name_editor_apply_filters)
    window.name_ids_table.itemSelectionChanged.connect(window._name_editor_on_id_selection_changed)
    window.name_missing_table.itemSelectionChanged.connect(window._name_editor_on_missing_selection_changed)
    window.info_search_edit.textChanged.connect(window._info_editor_apply_filters)
    window.info_ids_table.itemSelectionChanged.connect(window._info_editor_on_selection_changed)
    window.info_xml_edit.textChanged.connect(window._info_xml_text_changed)
    window.info_live_edit.textChanged.connect(window._info_live_text_changed)
    window.info_fmt_bold_btn.clicked.connect(lambda checked: window._info_live_set_char_style("bold", checked))
    window.info_fmt_italic_btn.clicked.connect(lambda checked: window._info_live_set_char_style("italic", checked))
    window.info_fmt_underline_btn.clicked.connect(lambda checked: window._info_live_set_char_style("underline", checked))
    window.name_subnav_name_btn.clicked.connect(lambda: window._set_name_editor_sub_view("name"))
    window.name_subnav_info_btn.clicked.connect(lambda: window._set_name_editor_sub_view("info"))
    window._set_name_editor_sub_view("name")
    window._info_xml_text_changed()
    return page
